// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf9tQfx8MERAuFVFWwOO79VB6UcJ9WAyY',
    appId: '1:995627818054:web:a9659bd290ab34f2a23e47',
    messagingSenderId: '995627818054',
    projectId: 'alituco-notes',
    authDomain: 'alituco-notes.firebaseapp.com',
    storageBucket: 'alituco-notes.appspot.com',
    measurementId: 'G-ELHYP98P39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7deRNNdvDhqoA7mTpUzrhxaXeyu_HZCQ',
    appId: '1:995627818054:android:3bc2824afdfb06f4a23e47',
    messagingSenderId: '995627818054',
    projectId: 'alituco-notes',
    storageBucket: 'alituco-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCac0-cDQztsH1--fMRJUUEIfn1zZf73_4',
    appId: '1:995627818054:ios:802dd62eca42eee1a23e47',
    messagingSenderId: '995627818054',
    projectId: 'alituco-notes',
    storageBucket: 'alituco-notes.appspot.com',
    iosBundleId: 'com.testingthisout.alisnotesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCac0-cDQztsH1--fMRJUUEIfn1zZf73_4',
    appId: '1:995627818054:ios:802dd62eca42eee1a23e47',
    messagingSenderId: '995627818054',
    projectId: 'alituco-notes',
    storageBucket: 'alituco-notes.appspot.com',
    iosBundleId: 'com.testingthisout.alisnotesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf9tQfx8MERAuFVFWwOO79VB6UcJ9WAyY',
    appId: '1:995627818054:web:0a5a6b963184e9f4a23e47',
    messagingSenderId: '995627818054',
    projectId: 'alituco-notes',
    authDomain: 'alituco-notes.firebaseapp.com',
    storageBucket: 'alituco-notes.appspot.com',
    measurementId: 'G-QVF2S67222',
  );
}
